[package]
name = "multicast-example"
version = "0.1.0"
authors = ["Brandon Richardson <brandon.richardson4328@outlook.com>"]
[dependencies]

lazy_static = "1.0"
socket2 = { version = "0.3.4", features = ["reuseport"] }